services:
  - type: web
    name: lms-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GOOGLE_API_KEY_1
        sync: false
      - key: DB_PATH
        value: /data/student_analyzer.db
    disk:
      name: lms-db-storage
      mountPath: /data
      sizeGB: 1
