services:
  - type: web
    name: lms-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GOOGLE_API_KEY_1
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lms-postgres
          property: connectionString

databases:
  - name: lms-postgres
    plan: free
